---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.0"
    name: elastic-role
  - src: git@github.com:Dozak/hw_8.4_kibana-role.git
    scm: git
    version: "1.0.0"
    name: kibana-role
  - src: git@github.com:Dozak/hw_8.4_filebeat-role.git
    scm: git
    version: "1.0.0"
    name: filebeat-role
